apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-count
            image: 0xd8c4eb/simple-counter:1.0.0
          restartPolicy: OnFailure
